# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDB

  #pod 'Alamofire', '~> 5.0.0-beta.5'
    pod 'Alamofire', '~> 4.7'
	pod 'ReachabilitySwift'
	pod 'SDWebImage', '~> 4.0.0'
    pod "XCDYouTubeKit", "~> 2.7"
  target 'MovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
